### ISSUE TITLE
Build not possible

### ISSUE THREAD

**Issue by Fireobirdy** [Canop/clima#5]
`:~/clima$ cargo install --path .
  Installing clima v0.0.5 (/home/june/clima)
    Updating crates.io index
  Downloaded log v0.4.8
  Downloaded lazy_static v1.4.0
  Downloaded clap v2.33.0
  Downloaded crossterm v0.14.2
  Downloaded cfg-if v0.1.10
  Downloaded ansi_term v0.11.0
  Downloaded atty v0.2.14
  Downloaded signal-hook v0.1.13
  Downloaded vec_map v0.8.1
  Downloaded textwrap v0.11.0
  Downloaded mio v0.6.21
  Downloaded unicode-width v0.1.7
  Downloaded libc v0.2.66
  Downloaded strsim v0.8.0
  Downloaded minimad v0.6.3
  Downloaded simplelog v0.6.0
  Downloaded custom_error v1.7.1
  Downloaded bitflags v1.2.1
  Downloaded parking_lot v0.10.0
  Downloaded iovec v0.1.4
  Downloaded chrono v0.4.10
  Downloaded signal-hook-registry v1.2.0
  Downloaded slab v0.4.2
  Downloaded term v0.5.2
  Downloaded net2 v0.2.33
  Downloaded parking_lot_core v0.7.0
  Downloaded num-traits v0.2.11
  Downloaded num-integer v0.1.42
  Downloaded termimad v0.8.13
  Downloaded time v0.1.42
  Downloaded lock_api v0.3.3
  Downloaded arc-swap v0.4.4
  Downloaded byteorder v1.3.4
  Downloaded autocfg v1.0.0
  Downloaded dirs v1.0.5
  Downloaded smallvec v1.2.0
  Downloaded crossbeam v0.7.3
  Downloaded scopeguard v1.0.0
  Downloaded crossterm v0.16.0
  Downloaded thiserror v1.0.10
  Downloaded crossbeam-deque v0.7.2
  Downloaded crossbeam-queue v0.2.1
  Downloaded crossbeam-channel v0.4.0
  Downloaded crossbeam-utils v0.7.0
  Downloaded crossbeam-epoch v0.8.0
  Downloaded autocfg v0.1.7
  Downloaded memoffset v0.5.3
  Downloaded thiserror-impl v1.0.10
  Downloaded rustc_version v0.2.3
  Downloaded quote v1.0.2
  Downloaded syn v1.0.14
  Downloaded semver v0.9.0
  Downloaded proc-macro2 v1.0.8
  Downloaded unicode-xid v0.2.0
  Downloaded semver-parser v0.7.0
   Compiling semver-parser v0.7.0
   Compiling autocfg v0.1.7
   Compiling libc v0.2.66
   Compiling proc-macro2 v1.0.8
   Compiling log v0.4.8
   Compiling autocfg v1.0.0
   Compiling unicode-xid v0.2.0
   Compiling lazy_static v1.4.0
   Compiling cfg-if v0.1.10
   Compiling syn v1.0.14
   Compiling scopeguard v1.0.0
   Compiling slab v0.4.2
   Compiling smallvec v1.2.0
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:35:1
   |
35 | pub extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
  --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:49:5
   |
49 | use core::mem::MaybeUninit;
   |     ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:294:12
    |
294 |     Inline(MaybeUninit<A>),
    |            ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:315:28
    |
315 |     fn from_inline(inline: MaybeUninit<A>) -> SmallVecData<A> {
    |                            ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:319:36
    |
319 |     unsafe fn into_inline(self) -> MaybeUninit<A> {
    |                                    ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:394:45
    |
394 |             data: SmallVecData::from_inline(MaybeUninit::uninit()),
    |                                             ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:434:63
    |
434 |                 let mut data = SmallVecData::<A>::from_inline(MaybeUninit::uninit());
    |                                                               ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:470:45
    |
470 |             data: SmallVecData::from_inline(MaybeUninit::new(buf)),
    |                                             ^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:489:55
    |
489 |         unsafe { SmallVec::from_buf_and_len_unchecked(MaybeUninit::new(buf), len) }
    |                                                       ^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:508:51
    |
508 |     pub unsafe fn from_buf_and_len_unchecked(buf: MaybeUninit<A>, len: usize) -> SmallVec<A> {
    |                                                   ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:670:55
    |
670 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
    |                                                       ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:737:55
    |
737 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
    |                                                       ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:1078:52
     |
1078 |                     let mut data: MaybeUninit<A> = MaybeUninit::uninit();
     |                                                    ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:1078:35
     |
1078 |                     let mut data: MaybeUninit<A> = MaybeUninit::uninit();
     |                                   ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:303:42
    |
303 |             SmallVecData::Inline(a) => a.as_ptr() as *const A::Item,
    |                                          ^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:310:42
    |
310 |             SmallVecData::Inline(a) => a.as_mut_ptr() as *mut A::Item,
    |                                          ^^^^^^^^^^

   Compiling arc-swap v0.4.4
error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:394:58
    |
394 |             data: SmallVecData::from_inline(MaybeUninit::uninit()),
    |                                             -------------^^^^^^
    |                                             |
    |                                             function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:434:76
    |
434 |                 let mut data = SmallVecData::<A>::from_inline(MaybeUninit::uninit());
    |                                                               -------------^^^^^^
    |                                                               |
    |                                                               function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:670:68
    |
670 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
    |                                                       -------------^^^^^^
    |                                                       |
    |                                                       function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:737:68
    |
737 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
    |                                                       -------------^^^^^^
    |                                                       |
    |                                                       function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0599]: no method named `assume_init` found for type `core::mem::MaybeUninit<A>` in the current scope
   --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:916:39
    |
916 |                 Ok(data.into_inline().assume_init())
    |                                       ^^^^^^^^^^^

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
    --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:1078:65
     |
1078 |                     let mut data: MaybeUninit<A> = MaybeUninit::uninit();
     |                                                    -------------^^^^^^
     |                                                    |
     |                                                    function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/june/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:1081:30
     |
1081 |                         data.as_mut_ptr() as *mut A::Item,
     |                              ^^^^^^^^^^

error: aborting due to 23 previous errors

Some errors occurred: E0599, E0658.
For more information about an error, try `rustc --explain E0599`.
error: Could not compile `smallvec`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clima v0.0.5 (/home/june/clima)`, intermediate artifacts can be found at `/home/june/clima/target`

Caused by:
  build failed
`

**Comment by Canop** [comment]
Can you please tell what version of rust you're using ?

    rustc --version

If you have a version before 1.40 please update.

**Comment by Fireobirdy** [comment]
`rustc ist schon die neueste Version (1.34.2+dfsg1-1).`

It is the actual version from debian buster, so up to date. If your project requires a newer version, would you please mention this on the readme-section? Thank you for the quick response!
