### ISSUE TITLE
Text inside inline code is not easy to see with light terminal theme

### ISSUE THREAD

**Issue by lamyergeier** [Canop/clima#8]
Text inside inline code is not easy to see:

![image](https://user-images.githubusercontent.com/42092626/127874229-ab7859ec-2c90-4672-b81e-6fb06dfada94.png)

**Comment by lamyergeier** [comment]
![image](https://user-images.githubusercontent.com/42092626/128575371-d4315c89-b84b-4732-ad5b-638e9e7eb0e8.png)

@Canop It works but may be it would be nice to have the background of inline code slightly darker than the background of normal text.

**Comment by Canop** [comment]
Right now the colors are the same whatever the background, because it's not easy to determine what's exactly the background in a terminal.

Side note: I'm curious as to what you're using clima for. Do you mind coming to [my chat](https://miaou.dystroy.org/3768) and discuss it ?

**Comment by Canop** [comment]
In the new 0.0.9, clima tries to determine whether the terminal has a dark or light background then choose among 3 skins accordingly.

With a light background:
![image](https://user-images.githubusercontent.com/617006/128767022-c77b4cad-1f85-4055-9488-35cf16539ed4.png)

With a dark background:
![image](https://user-images.githubusercontent.com/617006/128767089-b7c14ece-d953-4a89-8965-fa6bed69f632.png)
